#ifndef THINGER_HTTP_SERVER_ERROR_FORMAT_HPP
#define THINGER_HTTP_SERVER_ERROR_FORMAT_HPP

#include "../common/http_response.hpp"
#include "../../util/logger.hpp"
#include <nlohmann/json.hpp>
#include <functional>
#include <string>

namespace thinger::http {

// Error answered with response::error(), or generated by the server itself (invalid JSON
// body, schema validation, 404/405, 413, 500...)
struct http_error {
    http_response::status status;

    // Error message, empty if none was given (http_response::get_reason_phrase(status)
    // gives a generic one)
    std::string message;

    // Additional data, null if none; e.g. {"context": ["<root>", "[name]"]} for schema
    // validation errors (the location of the invalid value)
    nlohmann::json details;
};

// Writes the body of an error response (content, content type and any extra header);
// the status is already set
using error_formatter = std::function<void(const http_error& error, http_response& response)>;

// Default format: the message as text/plain, or, for errors with details, the JSON object
// {"error": {"message": <message>, <details>...}}
inline void default_error_formatter(const http_error& error, http_response& response) {
    if (error.details.is_null()) {
        response.set_content(error.message, "text/plain");
        return;
    }
    nlohmann::json body = {{"error", {{"message", error.message}}}};
    if (error.details.is_object()) {
        body["error"].update(error.details);
    } else {
        body["error"]["details"] = error.details;
    }
    response.set_content(body.dump(), "application/json");
}

// Format an error with `formatter`, or in the default format if there is none (or it fails)
inline void format_error(const error_formatter* formatter, const http_error& error, http_response& response) {
    if (formatter && *formatter) {
        try {
            (*formatter)(error, response);
            return;
        } catch (const std::exception& e) {
            LOG_ERROR("Error formatter failed: {}", e.what());
        }
    }
    default_error_formatter(error, response);
}

} // namespace thinger::http

#endif // THINGER_HTTP_SERVER_ERROR_FORMAT_HPP
